---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: virtualization-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/redhat-cop/gitops-catalog'
      targetRevision: HEAD
      path: virtualization-operator/operator/base
  project: default
  syncPolicy:
    automated:
      prune: false
      allowEmpty: true
