---
# duplicated from https://github.com/dlbewley/demo-metallb/blob/main/argo-cfg.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nmstate-config
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/dlbewley/demo-nmstate'
      targetRevision: HEAD
      path: instance/base
  project: default
  syncPolicy:
    automated:
      prune: false
      allowEmpty: true
