---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-hub-config
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/dlbewley/scratch-gitops'
      targetRevision: HEAD
      path: cluster/hub/
  project: default
  syncPolicy:
    automated:
      prune: false
      allowEmpty: true
