apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application.yaml
  # sync-wave 4
  # sync-wave 5
  - ../../argo-apps/olm/local-storage/
  - ../../argo-apps/olm/metallb/
  - ../../argo-apps/olm/nmstate/
  - ../../argo-apps/olm/rhacm/
  - ../../argo-apps/olm/odf/
  - ../../argo-apps/olm/virtualization/
  # sync-wave 9
  - ../../argo-apps/cfg/local-storage/
  - ../../argo-apps/cfg/odf/
  # sync-wave 10
  - ../../argo-apps/cfg/nmstate/
  - ../../argo-apps/cfg/metallb/
  - ../../argo-apps/cfg/homelab-net/

