---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nmstate-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/redhat-cop/gitops-catalog'
      targetRevision: main
      path: nmstate/operator/overlays/stable
  project: default
  syncPolicy:
    automated:
      prune: false
      allowEmpty: true
