---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhacm-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    #  labels:
    #has-git-repo-objects: "true"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/redhat-cop/gitops-catalog'
      targetRevision: main
      path: advanced-cluster-management/operator/overlays/release-2.11
  project: default
  syncPolicy:
    automated:
      prune: false
      allowEmpty: true
