apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2024-07-23T00:34:03Z"
  generation: 8
  name: gui-made
  namespace: openshift-gitops
  resourceVersion: "5981676"
  uid: 8d4baf97-b570-4a99-ae41-11a8cd747bad
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: cluster/hub
    repoURL: https://github.com/dlbewley/scratch-gitops.git
    targetRevision: HEAD
status:
  controllerNamespace: openshift-gitops
  health:
    status: Healthy
  operationState:
    finishedAt: "2024-07-23T00:43:52Z"
    message: one or more synchronization tasks are not valid
    operation:
      initiatedBy:
        username: kube:admin
      retry: {}
      sync:
        revision: f2a0e775a530a55bc9c4a828d6083fae67ee719b
        syncStrategy:
          hook: {}
    phase: Failed
    startedAt: "2024-07-23T00:43:52Z"
    syncResult:
      resources:
      - group: kustomize.config.k8s.io
        kind: Kustomization
        message: The Kubernetes API could not find kustomize.config.k8s.io/Kustomization
          for requested resource default/. Make sure the "Kustomization" CRD is installed
          on the destination cluster.
        name: ""
        namespace: default
        status: SyncFailed
        syncPhase: Sync
        version: v1beta1
      revision: f2a0e775a530a55bc9c4a828d6083fae67ee719b
      source:
        directory:
          jsonnet: {}
          recurse: true
        path: cluster/hub
        repoURL: https://github.com/dlbewley/scratch-gitops.git
        targetRevision: HEAD
  reconciledAt: "2024-07-23T00:43:52Z"
  resources:
  - health:
      status: Missing
    kind: Namespace
    name: demo-virt
    status: OutOfSync
    version: v1
  - group: kustomize.config.k8s.io
    health:
      status: Missing
    kind: Kustomization
    namespace: default
    status: OutOfSync
    version: v1beta1
  sourceType: Directory
  summary: {}
  sync:
    comparedTo:
      destination:
        namespace: default
        server: https://kubernetes.default.svc
      source:
        directory:
          jsonnet: {}
          recurse: true
        path: cluster/hub
        repoURL: https://github.com/dlbewley/scratch-gitops.git
        targetRevision: HEAD
    revision: f2a0e775a530a55bc9c4a828d6083fae67ee719b
    status: OutOfSync
